In [ ]:
#first code snippet
marks = [68, 49, 73, 80]
avg = (sum(marks)/len(marks))
print(avg)

67.5


In [ ]:
#Second Code Snippet
def calculate_average(marks):
  return sum(marks)/len(marks)

marks = [68, 49, 73, 80]
avg = calculate_average(marks)
print(avg)


67.5


In [ ]:
# reusable function with parameter

def check_result(marks):
    if marks >= 27:
        return "Pass"
    else:
        return "Fail"

students = [45, 20, 27, 10, 35]


for mark in students:
    print(mark, ":", check_result(mark))

45 : Pass
20 : Fail
27 : Pass
10 : Fail
35 : Pass


In [ ]:
# Python List
# General Purpose,
# can hold any data types or mixed data types,
# normal programming,
# operations need loops

In [ ]:
# Numpy
# Numerical Data Focused,
#  ususally hold one main numerical data type,
#  mathematical operations,
#  operatiojn can be apply to whole array

In [ ]:
import numpy as np

marks = [78, 46, 81]

print(np.array(marks) + 10)

[88 56 91]


In [ ]:
#shape: the structure of the array
#index:the position of the an element
#axis: direction of the calculation across rows or columns or XYZ axis

import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)


matrix =np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [ ]:
#slicing
grid = np.array([
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45],
    [51,52,53,54,55]
])
#First Element
print(grid[0,0])
#First Row
print(grid[0, ])
#First Column
print(grid[:,0])
#Middle 3*3 Matrix
print(grid[1:4, 1:4])


11
[11 12 13 14 15]
[11 21 31 41 51]
[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
marks = np.array([78, 48, 91, 65])

print(marks.mean())
print(marks.max())
print(marks.min())
print(marks.sum())

70.5
91
48
282


In [ ]:
import numpy as np

marks = np.array([78, 91, 55, 72, 40, 88, 98, 81, 11, 23, 78, 88, 91, 96])

# 1. First the class average
average = np.mean(marks)
print(f"Class Average: {average:.2f}")

# 2. Find the highest score
highest = np.max(marks)
print(f"Highest Score: {highest}")

# 3. Find the lowest score
lowest = np.min(marks)
print(f"Lowest Score: {lowest}")

# 4. Count students above 75
count_above_75 = np.sum(marks > 75)
print(f"Students above 75: {count_above_75}")


Class Average: 70.71
Highest Score: 98
Lowest Score: 11
Students above 75: 9


In [ ]:
from google.colab import files
uploaded =files.upload()

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
math_scores = df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())


[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [ ]:
# calculate the average score across the other two subjects
# Filtering



df["average"] = df[["math", "science", "english"]].mean(axis=1)
print(df[["name", "math", "science", "english", "average"]])

top_students = df[df["average"] >= 85]
print(top_students[["name", "average"]])





      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667
      name    average
1     Diya  

In [ ]:
# #low attendance, if attendance percentage is less than 75 then


# Filter for students attendance less than 75%
low_attendance = df[df["attendance_percent"] < 75]
print(low_attendance[["name", "attendance_percent"]])



      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


In [ ]:
# mathura students, name, city, average

# Filter rows for Mathura, then select the specific columns
mathura_students = df[df["city"] == "Mathura"]
print(mathura_students[["name", "city", "average"]])

      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000


In [ ]:
import pandas as pd
#STUDENT PERFORMANCE ANALYSER

# Read session4_dummy_students.csv.

df = pd.read_csv("session4_dummy_students_data.csv")
print(df)

# Create an average column using math, science, and english.

df['average'] = (df['math'] + df['science'] + df['english']) / 3
print(df[['name', 'average']])


      name    average
0    Aarav  77.000000
1     Diya  91.000000
2    Kabir  58.000000
3    Meera  77.333333
4    Rohan  46.333333
5     Sara  90.333333
6   Ishaan  66.666667
7   Ananya  92.000000
8   Vivaan  52.000000
9     Tara  81.333333
10   Arjun  67.333333
11   Nisha  78.000000
12     Dev  40.666667
13   Priya  88.666667
14   Kunal  57.333333
15    Riya  92.666667
16      Om  65.000000
17   Aditi  82.666667
18    Yash  46.000000
19   Sneha  76.666667


In [ ]:
# 4. Print class average
class_avg = df['average'].mean()
print(f"Class Average: {class_avg:.2f}\n")

Class Average: 71.35



In [ ]:
# 5. Print subject wise averages
print("Subject-wise Averages:")
print(f" - Science: {df['science'].mean():.2f}")
print(f" - English: {df['english'].mean():.2f}")
print(f" - Math: {df['math'].mean():.2f}\n")

Subject-wise Averages:
 - Science: 72.35
 - English: 72.20
 - Math: 69.50



In [ ]:
# 6. Find and print the top student(s)
highest_score = df['average'].max()
top_students = df[df['average'] == highest_score]
print("Top Student(s):")
print(top_students[['name', 'average']])
print()

Top Student(s):
    name    average
15  Riya  92.666667



In [ ]:
# 7. Print students with attendance below 75
low_attendance = df[df['attendance_percent'] < 75]
print("Students with attendance below 75%:")
print(low_attendance[['name', 'attendance_percent']])
print()

Students with attendance below 75%:
      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66



In [ ]:
# 8. Print students who submitted fewer than 6 assignments
few_assignments = df[df['assignments_submitted'] < 6]
print("Students who submitted fewer than 6 assignments:")
print(few_assignments[['name', 'assignments_submitted']])

Students who submitted fewer than 6 assignments:
     name  assignments_submitted
4   Rohan                      5
12    Dev                      4
18   Yash                      5
